# Generated by Django 5.2.7 on 2025-11-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
