# Generated by Django 5.2.7 on 2025-11-01 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_students", "0002_alter_evaluation_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="model_students.course",
                verbose_name="Materia Inscrita",
            ),
        ),
    ]
